### ISSUE TITLE
Getting error on running 'gulp serve'.

### ISSUE THREAD

**Issue by nikkiana** [scottnath/generator-pattern-library#11]
```
at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
at Gulp.emit (events.js:129:20)
at Gulp.Orchestrator._emitTaskDone (/Users/nikkiana/Sites/generator-pattern-library/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
at /Users/nikkiana/Sites/generator-pattern-library/node_modules/gulp/node_modules/orchestrator/index.js:275:23
at finish (/Users/nikkiana/Sites/generator-pattern-library/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
at ChildProcess.cb (/Users/nikkiana/Sites/generator-pattern-library/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
at ChildProcess.emit (events.js:110:17)
at maybeClose (child_process.js:1015:16)
at Socket.<anonymous> (child_process.js:1183:11)
```

**Comment by scottnath** [comment]
@nikkiana please close this issue if an installation of composer fixes this

**Comment by scottnath** [comment]
@nikkiana is this working correctly for you now? Were you able to get the latest version?

**Comment by nikkiana** [comment]
@scottnath yep, all good now.
