### ISSUE TITLE
creating pattern throws error

### ISSUE THREAD

**Issue by rebmullin** [scottnath/generator-pattern-library#3]
i get the following error when I attempt to create a pattern: http://grab.by/K1eE.  Do I need to install additional modules to get this to work?

**Comment by scottnath** [comment]
@rebmullin can you please revisit and see if you're still getting this error?

**Comment by rebmullin** [comment]
@scottnath  - looking good now.

**Comment by e2tha-e** [comment]
@scottnath @rebmullin Still not working. I deleted and reinstalled many times:

System:
- OS X 10.10.5 Yosemite
- Node.js v0.12.2
- NPM v2.14.2
- yo v1.4.7

generator-pattern-library git:(master) ✗ yo pattern-library:pattern
module.js:338
    throw err;
          ^
Error: Cannot find module '../../utils'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-pattern-library/generators/pattern/index.js:6:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

**Comment by rebmullin** [comment]
hey @e2tha-e  - i think you need to reinstall the generator. Retry: `npm install -g generator-pattern-library`. I believe that should help...

**Comment by e2tha-e** [comment]
@rebmullin @scottnath Reinstalling generator-pattern-library worked. Thanks!

**Comment by rebmullin** [comment]
cool @e2tha-e  : )

**Comment by scottnath** [comment]
@e2tha-e @rebmullin 

that's great! can we close this issue?

**Comment by rebmullin** [comment]
@scottnath  it's already closed  : )
